---
title: ""
---

### Materiales para Teoría

-   [Slides Tema 1](./econometria_gadedret/slides_tema_1.html){target="_blank"}         [Slides tema 2](./econometria_gadedret/slides_tema_2.html){target="_blank"}

-   [Slides tema 3](./econometria_gadedret/slides_tema_3.html){target="_blank"}         [Slides tema 4](./econometria_gadedret/slides_tema_4.html){target="_blank"}

-   [Slides tema 5](./econometria_gadedret/slides_tema_5.html){target="_blank"}          [Slides tema 6](./econometria_gadedret/slides_tema_6.html){target="_blank"} 

- [Slides tema 7](./econometria_gadedret/slides_tema_7.html){target="_blank"}        [Ejemplos de aplicación](./econometria_gadedret/ejemplos_de_aplicacion.html){target="_blank"}


### Materiales para prácticas

-   [Cuestionario](./econometria_gadedret/cuestionario_practicas.html){target="_blank"}

-   [Datos](./econometria_gadedret/datos.zip){target="_blank"}

-   [Tablas de probabilidad](./econometria_gadedret/tablas_probabilidad.pdf){target="_blank"}

-   [Etherpad](https://etherpad.wikimedia.org/p/curso_intro_DS_UV){target="_blank"}


### Descarga materiales

- Puedes descargarte todos los materiales en formato pdf [aquí]()



